### ISSUE TITLE
inputs files form some subdirectories but not others

### ISSUE THREAD

**Issue by GoogleCodeExporter** [keredson/desigle#3]
```
What steps will reproduce the problem?
1. open attached includetest.tar.gz
2. ./desigle includetest.tex
3. uncomment line: \input{subdirectory2/includetest3}

What is the expected output? What do you see instead?
Should include content from all files, but has trouble with second
subdirectory. Instead, I get a message something like "can't find file
subdirectory2/includetest3.tex"

What version of the product are you using? On what operating system?
DeSiGLE v0.33 with TeXlive on Ubuntu 7.10 Gutsy Gibbon

Please provide any additional information below.
Even with the two subdirectories have identical contents I get the problem,
or just changing the name of the subdirectory can cause it to not get found


```

Original issue reported on code.google.com by `ian.g.ta...@gmail.com` on 23 Apr 2008 at 7:21

Attachments:
- [includetest.tar.gz](https://storage.googleapis.com/google-code-attachments/desigle/issue-3/comment-0/includetest.tar.gz)

**Comment by GoogleCodeExporter** [comment]
```
Tried to look at issue in v0.34 and got the following:

ian@ian-thinkpad:~/desigle$ ./desigle.py /home/ian/desigle/test/includetest.tex 
Traceback (most recent call last):
  File "./desigle.py", line 872, in <module>
    main_gui.open_file(sys.argv[1])
  File "./desigle.py", line 750, in open_file
    self.refresh_preview()
  File "./desigle.py", line 688, in refresh_preview
    if fname in include_files or fname_base in include_files:
UnboundLocalError: local variable 'fname_base' referenced before assignment

```

Original comment by `ian.g.ta...@gmail.com` on 25 Apr 2008 at 12:43

**Comment by GoogleCodeExporter** [comment]
Original comment by `pub...@kered.org` on 20 Apr 2009 at 9:17
- Changed state: **Duplicate**
