### ISSUE TITLE
Error opening a file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [keredson/desigle#7]
```
What steps will reproduce the problem?
1. Opening a file named 01.tex or sth like that


What is the expected output? What do you see instead?
Traceback (most recent call last):
  File "/opt/desigle/desigle.py", line 445, in <lambda>
    self.ui.get_widget('toolbutton_open').connect('clicked', lambda x:
self.open())
  File "/opt/desigle/desigle.py", line 745, in open
    self.open_file( filename )
  File "/opt/desigle/desigle.py", line 760, in open_file
    self.refresh_preview()
  File "/opt/desigle/desigle.py", line 697, in refresh_preview
    if fname in include_files or fname_base in include_files:
UnboundLocalError: local variable 'fname_base' referenced before assignment
Traceback (most recent call last):
  File "desigle.py", line 817, in watch_editor
    self.refresh_preview()
  File "desigle.py", line 697, in refresh_preview
    if fname in include_files or fname_base in include_files:
UnboundLocalError: local variable 'fname_base' referenced before assignment


What version of the product are you using? On what operating system?
current SVN Version. Ubuntu Intrepid

Please provide any additional information below.
I added a line in line 695 like that to introduce fname_base:
fname_base = ''
This one works for me.
```

Original issue reported on code.google.com by `grimm.ma...@gmail.com` on 4 Nov 2008 at 10:38

**Comment by GoogleCodeExporter** [comment]
```
fixed in svn
```

Original comment by `pub...@kered.org` on 20 Apr 2009 at 9:14
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Issue 3 has been merged into this issue.
```

Original comment by `pub...@kered.org` on 20 Apr 2009 at 9:17
